AliCRM/AliCRM/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crmweb/', include("crmweb.urls")),
    url(r'^rbac/', include("rbac.urls")),
    url(r'^student/', include("student.urls")),
]

AliCRM/rbac/urls.py
from rbac.views import permission_distribute
from django.conf.urls import url

urlpatterns = [
    url(r'^permission/distribute/', permission_distribute.PermissionDistribute.as_view(), name="distribute")
]

AliCRM/rbac/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# 身份分类
identity_choices = (
    ("1", "董事"),
    ("2", "CEO"),
    ("3", "销售"),
    ("4", "网咨"),
    ("5", "老师"),
    ("6", "班主任"),
)

# 扩展的用户表
class UserInfo(AbstractUser):
    """用户信息表:老师，助教，销售，班主任"""
    id = models.AutoField(primary_key=True)
    gender_type = (("male", "男"), ("female", "女"))
    gender = models.CharField(choices=gender_type, null=True, max_length=12)
    phone = models.CharField(max_length=11, null=True, unique=True)
    role = models.ManyToManyField("Role")

    def __str__(self):
        return self.username


# 身份表
class Role(models.Model):
    title = models.CharField("职位", choices=identity_choices, max_length=32)
    permission = models.ManyToManyField("Permission")

    def __str__(self):
        return self.title


# 权限表
class Permission(models.Model):
    name = models.CharField(max_length=32, verbose_name=u'菜单名')
    url = models.CharField(
        max_length=300,
        verbose_name=u'权限url地址',
        null=True,
        blank=True,
        help_text=u'是否给菜单设置一个url地址'
    )
    icon = models.CharField(
        max_length=32,
        verbose_name='二级菜单图标',
        null=True,
        blank=True
    )

    parent = models.ForeignKey(
        'self',
        verbose_name=u'父级菜单',
        null=True,
        blank=True,
        help_text=u'如果添加的是子菜单，请选择父菜单'
    )
    show = models.BooleanField(
        verbose_name=u'是否显示',
        default=False,
        help_text=u'菜单是否显示，默认添加不显示'
    )
    priority = models.IntegerField(
        verbose_name=u'显示优先级',
        null=True,
        blank=True,
        help_text=u'菜单的显示顺序，优先级越小显示越靠前'
    )

    def __str__(self):
        return "{parent}{name}".format(name=self.name, parent="%s-->" % self.parent.name if self.parent else '')

    class Meta:
        verbose_name = u"权限表"
        verbose_name_plural = u"权限表"
        ordering = ["priority","id"]

AliCRM/rbac/views/permission_distribute.py
from django import views
from django.shortcuts import (
    render,reverse,redirect,HttpResponse
)
from rbac import models

class PermissionDistribute(views.View):

    def get(self,request):
        uid = request.GET.get('uid')
        user = models.UserInfo.objects.filter(id=uid)
        rid = request.GET.get('rid')

        # 获取所有用户
        all_user = models.UserInfo.objects.all()
        # 获取所有角色
        all_role = models.Role.objects.all()

        # 获取所有权限
        all_permission = models.Permission.objects.all().order_by("pk")
        if uid:  # 如果用户选中了用户id
            all_role_list = models.UserInfo.objects.get(pk=uid).role.values_list("pk")
            all_role_list = [i[0] for i in all_role_list]  # 转换成列表
            if rid:
                # 如果选中了角色，查找该角色的所有权限
                all_permission_list = models.Role.objects.filter(pk=rid).values_list("permission__pk")
            else:
                # 如果没有选中角色，就查找该用户的所有角色的所有权限，并去重
                all_permission_list = models.UserInfo.objects.get(pk=uid).role.values_list("permission__pk").distinct()
            all_permission_list = [i[0] for i in all_permission_list]  # 转换为列表
        else:
            if rid:
                all_permission_list = models.Role.objects.filter(pk=rid).values_list("permission__pk")
                all_permission_list = [i[0] for i in all_permission_list]  # 转换为列表

        return render(request,"permission_distribute.html",locals())

    def post(self,request):
        uid = request.GET.get('uid')
        user = models.UserInfo.objects.filter(id=uid)
        rid = request.GET.get('rid')

        postType = request.POST.get("postType")
        if postType == "role":
            role_list = request.POST.getlist("role_id")
            user.first().role.set(role_list)

        if postType == "permission":
            permission_list = request.POST.getlist("permission_id")
            print(permission_list)
            models.Role.objects.filter(pk=rid).first().permission.set(permission_list)

        url = reverse("distribute") + f"?uid={uid}&rid={rid}"
        return redirect(url)

AliCRM/rbac/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% for menu in menus_list %}
    {% if menu.children %}
        <li class="treeview {{ menu.class }}">
            <a href="">
                <i class="fa {{ menu.icon }}"></i>
                <span>{{ menu.name }}</span>
                <span class="pull-right-container">
                    <span class="fa fa-angle-left pull-right"></span>
                </span>
            </a>
            <ul class="treeview-menu">
                {% for child_menu in menu.children %}
                    <li class="{{ child_menu.class }}">
                        <a href="{{ child_menu.url }}">
                            <i class="fa fa-circle-o"></i> {{ child_menu.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </li>

    {% else %}
        <li class="{{ menu.class }}">
            <a href="{{ menu.url }}">
                <i class="fa {{ menu.icon }}"></i>
                <span>{{ menu.name }}</span>
                <span class="pull-right-container">
                </span>
            </a>
        </li>
    {% endif %}
{% endfor %}

</body>
</html>

AliCRM/rbac/templates/permission_distribute.html
{% extends 'BASE.html' %}
{% load static %}
{% block head %}
    {{ block.super }}
{% endblock head %}
{% block title %}
    客户跟进信息
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    <div class="col-sm-2  user-area">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title"><i class="fa fa-user"> 用户表</i></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body no-padding">
                                <table class="table text-center">
                                    <tbody>
                                    <tr>
                                        <th>用户选择</th>
                                    </tr>
                                    {% for user in all_user %}
                                        <tr class={% if user.pk|safe == uid %} "active danger" {% endif %}>
                                            <td><a class="btn btn-info btn-xs"
                                                   href="?uid={{ user.pk }}">{{ user.username }}</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                    <div class="col-sm-3  identity-area">
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="postType" value="permission">
                            <div class="box">

                                <div class="box-header">
                                    <h3 class="box-title"><i class="fa fa-id-card"> 角色表</i></h3>
                                    {% if uid %}
                                        <button class="btn btn-warning pull-right">保存</button>
                                    {% endif %}
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body no-padding">
                                    <table class="table text-center">
                                        <tbody>
                                        <tr>
                                            <th>角色</th>
                                            <th>选择</th>
                                        </tr>
                                        {% load rbac %}
                                        {% for role in all_role %}
                                            <tr class={% if role.pk|safe == rid %} "active danger" {% endif %}>
                                                <td><a class="btn btn-info btn-xs"
                                                       href="?{% get_role_url request role.pk %}">{{ role.get_title_display }}</a>
                                                </td>
                                                {% if role.pk in all_role_list %}
                                                    <td><input type="checkbox" name="role_id" checked
                                                               value="{{ role.pk }}"></td>
                                                {% else %}
                                                    <td><input type="checkbox" name="role_id" value="{{ role.pk }}">
                                                    </td>
                                                {% endif %}

                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>

                                <!-- /.box-body -->
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-5  permission-area">
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="postType" value="permission">
                            <div class="box">
                                <div class="box-header success">
                                    <h3 class="box-title"><i class="fa fa-cubes"> 权限表</i></h3>
                                    {% if rid %}
                                        <button class="btn btn-warning pull-right">保存</button>
                                    {% endif %}
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body no-padding">
                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <th>一级</th>
                                            <th>二级</th>
                                            <th>子权限</th>
                                        </tr>
                                        {% for permission in all_permission %}

                                            {% if not permission.parent %}
                                                <tr>
                                                    <td class="btn-default master"><input type="checkbox"
                                                                                          name="permission_id"
                                                            {% if permission.pk in all_permission_list %}
                                                                                          checked {% endif %}
                                                                                          value="{{ permission.pk }}">{{ permission.name }}
                                                    </td>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            {% else %}
                                                {% if permission.show %}
                                                    <tr>
                                                        <td></td>
                                                        <td><input type="checkbox" name="permission_id"
                                                                {% if permission.pk in all_permission_list %}
                                                                   checked {% endif %}
                                                                   value="{{ permission.pk }}">{{ permission.name }}
                                                        </td>
                                                        <td></td>
                                                    </tr>
                                                {% else %}
                                                    <tr>
                                                        <td></td>
                                                        <td></td>
                                                        <td><input type="checkbox" name="permission_id"
                                                                {% if permission.pk in all_permission_list %}
                                                                   checked {% endif %}
                                                                   value="{{ permission.pk }}">{{ permission.name }}
                                                        </td>
                                                    </tr>
                                                {% endif %}

                                            {% endif %}
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.box-body -->
                            </div>
                        </form>
                    </div>

                </div>

                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
{% endblock content %}
{% block js %}
    {{ block.super }}
{% endblock js %}

{% block customjs %}
    <script>
        $("[name=batch_choose]").click(function () {
            var status = $(this).prop("checked");
            $("[name=choose]").prop('checked', status)
        });
    </script>

    <script>
        $("#master").click(function () {

        })
    </script>
    {{ jump_js|safe }}
{% endblock customjs %}