AliCRM/AliCRM/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crmweb/', include("crmweb.urls")),
    url(r'^rbac/', include("rbac.urls")),
    url(r'^student/', include("student.urls")),
]

AliCRM/rbac/urls.py
from rbac.views import permission_distribute
from django.conf.urls import url

urlpatterns = [
    url(r'^permission/distribute/', permission_distribute.PermissionDistribute.as_view(), name="distribute")
]

AliCRM/student/urls.py
from student.views import students
from django.conf.urls import url

urlpatterns = [
    # 班级学习记录展示
    url(r'^class/study/record/list/', students.ClassStudyRecord.as_view(), name="class_study_record"),

    # 学员学习记录展示
    url(r'^student/study/record/list/(\d+)?/?', students.StudentStudyRecord.as_view(), name="student_study_record"),
]

AliCRM/student/models.py
from django.db import models

# Create your models here.

# 成绩选项
score_choices = (
    (100, 'A+'),
    (90, 'A'),
    (85, 'B+'),
    (80, 'B'),
    (70, 'B-'),
    (60, 'C+'),
    (50, 'C'),
    (40, 'C-'),
    (0, ' D'),
    (-1, 'N/A'),
    (-100, 'COPY'),
    (-1000, 'FAIL'),
)

# 记录选项
record_choices = (
    ('checked', "已签到"),
    ('vacate', "请假"),
    ('late', "迟到"),
    ('absence', "缺勤"),
    ('leave_early', "早退"),
)


class Student(models.Model):
    """
    学生表（已报名）
    """
    customer = models.OneToOneField(verbose_name='客户信息', to='crmweb.Customer', on_delete=models.CASCADE, null=True,blank=True)

    class_list = models.ManyToManyField(verbose_name="已报班级", to='crmweb.ClassList', blank=True, related_name="students")

    emergency_contract = models.CharField(max_length=32, blank=True, null=True, verbose_name='紧急联系人')

    # 学员毕业就业后的相关信息字段，默认为空
    company = models.CharField(verbose_name='公司', max_length=128, blank=True, null=True)
    date = models.DateField(verbose_name='入职时间', help_text='格式yyyy-mm-dd', blank=True, null=True)
    location = models.CharField(max_length=64, verbose_name='所在区域', blank=True, null=True)
    position = models.CharField(verbose_name='岗位', max_length=64, blank=True, null=True)
    salary = models.IntegerField(verbose_name='薪资', blank=True, null=True)
    welfare = models.CharField(verbose_name='福利', max_length=256, blank=True, null=True)
    memo = models.CharField(verbose_name='备注', max_length=256, blank=True, null=True)

    def __str__(self):
        return self.customer.name


class ClassStudyRecord(models.Model):
    """
    上课记录表 （班级记录）
    """
    class_obj = models.ForeignKey(verbose_name="班级", to="crmweb.ClassList", on_delete=models.CASCADE)
    day_num = models.IntegerField(verbose_name="节次", help_text=u"此处填写第几节课或第几天课程...,必须为数字")
    teacher = models.ForeignKey(verbose_name="讲师", to='rbac.UserInfo', on_delete=models.CASCADE)
    date = models.DateField(verbose_name="上课日期")
    course_title = models.CharField(verbose_name='本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField(verbose_name='本节课程内容概要', blank=True, null=True)
    has_homework = models.BooleanField(default=False, verbose_name="本节有作业", blank=True)
    homework_title = models.CharField(verbose_name='本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField(verbose_name='作业描述', max_length=500, blank=True, null=True)
    exam = models.TextField(verbose_name='得分点', max_length=300, blank=True, null=True)

    def __str__(self):
        return "{0} day{1}".format(self.class_obj, self.day_num)


class StudentStudyRecord(models.Model):
    '''
    学生学习记录
    '''
    student = models.ForeignKey(verbose_name="学员", to='Student', on_delete=models.CASCADE)
    class_study_record = models.ForeignKey(verbose_name="第几天课程", to="ClassStudyRecord", on_delete=models.CASCADE)

    record = models.CharField("上课纪录", choices=record_choices, default="checked", max_length=64)
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)

    homework = models.FileField(verbose_name='作业文件', blank=True, null=True, default=None)
    stu_memo = models.TextField(verbose_name='学员备注', blank=True, null=True)
    date = models.DateTimeField(verbose_name='提交作业日期', auto_now_add=True)

    homework_note = models.CharField(verbose_name='作业评语', max_length=255, blank=True, null=True)
    note = models.CharField(verbose_name="备注", max_length=255, blank=True, null=True)

    def __str__(self):
        return "{0}-{1}".format(self.class_study_record, self.student)

    class Meta:
        unique_together = ["student", "class_study_record"]

AliCRM/student/views/students.py
from django import views
from student import models
from django.contrib import auth
from student.forms.formauth import StudentStudyRecordMF
from django.forms.models import modelformset_factory
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import (
    render, redirect, reverse, HttpResponse
)


# 班级学习记录视图
class ClassStudyRecord(views.View):
    @method_decorator(login_required)  # 校验用户登录
    def dispatch(self, request, *args, **kwargs):
        res = super().dispatch(request,*args,**kwargs)
        return res

    def get(self,request):
        # 获取所有班级的课程记录
        all_records = models.ClassStudyRecord.objects.all()
        return render(request,"class_study_record_list.html",{"all_records":all_records})

    def post(self,request):
        # 获取批量操作类型
        operate = request.POST.get("operate")
        # 获取批量提交的班级课程记录id
        selected_id = request.POST.getlist("choose")
        print(operate)
        if hasattr(self,operate):  # 反射类中的批量操作方法
            getattr(self,operate)(selected_id)
        return self.get(request)

    def batch_create(self,selected_id):
        for class_record_id in selected_id:
            # 根据班级课程记录查到多有的学生对象.
            # 注意班级和学生，一对多关联，通过班级反向找学生，类名小写_set.all()，但是外键字段取了related_name，所以直接使用别名students.all()
            all_students = models.ClassStudyRecord.objects.get(pk=class_record_id).class_obj.students.all()
            # print(all_students)
            # 给所有学生创建一条学习记录，只填好学生姓名，和所属的哪一节课程.
            li = []
            for student in all_students:
                # 根据每一个学生实例化一个学生学习记录对象
                student_record = models.StudentStudyRecord(
                    student=student,
                    class_study_record_id=class_record_id
                )
                li.append(student_record)
            # 批量创建记录
            models.StudentStudyRecord.objects.bulk_create(li)


# 学生学习记录视图,普通的
class StudentStudyRecord(views.View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        ret = super().dispatch(request,*args,**kwargs)
        return ret

    def get(self,request,class_record_id=None):
        if class_record_id:  # 有班级id，说明是批量修改请求
            # 通过modelformset批量修改
            ret = self.batch_edit_mfs(request,class_record_id)
        else:
            # 没有是数据展示请求
            ret = self.display(request)
        return ret

    def display(self,request):
        """
        直接请求学生学习记录展示的页面
        :param request:
        :return:
        """
        # 找到这节班级课程的所有学生学习记录
        all_records = models.StudentStudyRecord.objects.all()

        # 获取分数的可选选项
        score_choices = models.score_choices

        return render(request, "student_study_record_list.html",{"all_records": all_records,"score_choices": score_choices})

    """批量修改展示数据的两种方式"""
    # 第一种方式，通过手动遍历数据展示批量修改的数据列表
    def batch_edit(self,request,class_record_id):
        # 通过班级记录id，找到班级课程的那一条记录
        class_record_obj = models.ClassStudyRecord.objects.get(pk=class_record_id)

        # 通过班级对象，找到这节班级课程的所有学生学习记录
        all_records = models.StudentStudyRecord.objects.filter(class_study_record=class_record_obj)

        # 获取分数的可选选项
        score_choices = models.score_choices

        return render(request,"student_study_record_edit.html",{"class_record_obj":class_record_obj,"all_records":all_records,"score_choices":score_choices})

    # 第二种方式，通过使用modelformset来生成批量修改的页面
    def batch_edit_mfs(self,request,class_record_id):
        # 通过班级记录id，找到班级课程的那一条记录
        class_record_obj = models.ClassStudyRecord.objects.get(pk=class_record_id)

        # 通过班级对象，找到这节班级课程的所有学生学习记录
        all_records = models.StudentStudyRecord.objects.filter(
            class_study_record=class_record_obj,
        )

        # 实例化一个form_set对象
        form_set_obj = modelformset_factory(
            model=models.StudentStudyRecord,  # 指定一张表
            form=StudentStudyRecordMF,  # 指定一个modelform
            extra=0  # 可以指定生成表中，新建数据的行数，看页面效果就理解了
        )

        # 将所有的学生学习记录传给form_set对象的queryset
        all_records = form_set_obj(queryset=all_records)

        return render(request,"student_study_record_edit.html",{"class_record_obj":class_record_obj,"all_records":all_records})

    """批量提交修改数据的两种方式"""
    def post(self,request,class_record_id=None):
        # 调用不同的方式来批量修改数据
        self.batch_commit_mfs(request,class_record_id)

        return self.get(request,class_record_id)

    # 第一种方式，通过手动获取数据，提取数据结构来更新数据
    def batch_commit(self,request,class_record_id):
        data = request.POST
        # print(data)  # <QueryDict: {'csrfmiddlewaretoken': ['R73Lgac0jPy6YwP1guZ4fC5wLsrVY4iGgd45hip6xtcxZNfuiysmRwGt2IZhi0K0'], 'socre_1': ['80'], 'homework_note_1': ['请问'], 'socre_4': ['90'], 'homework_note_4': ['武器二人'], 'socre_5': ['100'], 'homework_note_5': ['未确认']}>

        # 构件我们想要的数据类型
        """
        {
            1:{"score":80,"homework_note":"123"},
            2:{"score":85,"homework_note":"456"},
        }
        """
        cleaned_data = {}
        for key,val in data.items():
            if key == "csrfmiddlewaretoken":continue
            field,pk = key.rsplit("_",1)
            if pk in cleaned_data:
                cleaned_data[pk].update({field:val})
            else:
                cleaned_data[pk] = {field:val}

        for pk,val in cleaned_data.items():
            models.StudentStudyRecord.objects.filter(pk=pk).update(**val)

    # 第二种方式，通过modelformset提供的save方法存储
    def batch_commit_mfs(self,request,class_record_id):
        # 通过班级记录id，找到班级课程的那一条记录
        class_record_obj = models.ClassStudyRecord.objects.get(pk=class_record_id)

        # 实例化一个form_set对象
        form_set_obj = modelformset_factory(
            model=models.StudentStudyRecord,  # 指定一张表
            form=StudentStudyRecordMF,  # 指定一个modelform
            extra=0  # 可以指定生成表中，新建数据的行数，看页面效果就理解了
        )
        print(request.POST)

        # 将提交的form数据传给form_set对象
        all_records = form_set_obj(request.POST)
        print(all_records)

        if all_records.is_valid():  # 对提交的数据进行验证
            all_records.save()  # 如果合法，则保存导数据
        else:  # 如果不合法，将错误的提示重新渲染到页面，
            print(all_records.errors)

AliCRM/student/templates/class_study_record_list.html
{% extends 'BASE.html' %}
{% load static %}
{% block head %}
    {{ block.super }}
{% endblock head %}
{% block title %}
    班级学习记录表
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    <form action="" method="get" class="navbar-form navbar-left">
                        <div class="input-group">
                            <div class="input-group-btn btn-info">
                                <select name="condition" id="search" class="btn input-group-sm btn-info"
                                        style="border: 0">
{#                                    <option value="customer">客户名</option>#}
{#                                    <option value="status">跟进状态</option>#}
                                </select>
                            </div>
                            <input type="text" name="q" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button type="submit" id="search-btn" class="btn btn-flat">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                    {% load rbac %}
{#                    {% if "/crmweb/consult/record/add/"|has_permission:request %}#}
                        <a href="" class="btn btn-primary pull-right">新增记录</a>
{#                    {% endif %}#}
                </div>

                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-6">

                        </div>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="input-group" style="width: 220px;margin-bottom: 5px;margin-left: 15px">
                            <select name="operate" id="operate" class="form-control btn-default">
                                <option value="batch_create">批量添加学生学习记录</option>
                            </select>
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-warning btn-flat">Go!</button>
                            </span>
                        </div>


                        <table id="example2" class="table table-bordered table-hover text-center">
                            <thead>
                            <tr>
                                <th style="width: 8%">
                                    <button type="button" class="btn btn-info btn-xs"><input
                                            type="checkbox" name="batch_choose"></button>
                                </th>
                                <th style="width: 5%">序号</th>
                                <th>班级</th>
                                <th>节次</th>
                                <th>老师</th>
                                <th>课程标题</th>
                                <th>学习详情</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for record in all_records %}
                                <tr>
                                    <td><input type="checkbox" name="choose" value="{{ record.pk }}"></td>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ record.class_obj }}</td>
                                    <td>{{ record.day_num }}</td>
                                    <td>{{ record.teacher }}</td>
                                    <td>{{ record.course_title|default:"暂无" }}</td>
                                    <td><a href="{% url 'student_study_record' record.pk %}">查看</a></td>
                                    <td>
                                        <a style="color: #00c3cc;" href="">
                                            <i class="fa fa-edit" aria-hidden="true"></i>
                                        </a>
                                        |
                                        <a style="color: #d9534f;" href="" >
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                        {% if not all_records %}
                            <h3 class="text-center">没有相关记录！</h3>
                        {% endif %}

                        <div class="pull-right" style="display:inline-block; width: 120px;margin: 22px 10px">
                            {{ jump_tag|safe }}
                        </div>

                        <div class="pull-right">
                            {{ paginator_tag|safe }}
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
{% endblock content %}
{% block js %}
    {{ block.super }}
{% endblock js %}

{% block customjs %}
    <script>
        $("[name=batch_choose]").click(function () {
            var status = $(this).prop("checked");
            $("[name=choose]").prop('checked', status)
        });
    </script>
{#    {{ jump_js|safe }}#}
{% endblock customjs %}

AliCRM/student/templates/student_study_record_edit.html
{% extends 'BASE.html' %}
{% load static %}
{% block head %}
    {{ block.super }}
{% endblock head %}
{% block title %}
    学员学习记录
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="text-center">{{ class_record_obj.class_obj }}-day{{ class_record_obj.day_num }}天-成绩录入</h3>
                    <form action="" method="get" class="navbar-form navbar-left">
                        <div class="input-group">
                            <div class="input-group-btn btn-info">
                                <select name="condition" id="search" class="btn input-group-sm btn-info"
                                        style="border: 0">
                                    {#                                    <option value="customer">客户名</option>#}
                                    {#                                    <option value="status">跟进状态</option>#}
                                </select>
                            </div>
                            <input type="text" name="q" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button type="submit" id="search-btn" class="btn btn-flat">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                    {% load rbac %}
                    <a href="{% url 'consult_record_add' %}" class="btn btn-primary pull-right">新增记录</a>


                </div>

                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-6">

                        </div>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="input-group" style="width: 220px;margin-bottom: 5px;margin-left: 15px">
                            <select name="operate" id="operate" class="form-control btn-default">
                            </select>
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-warning btn-flat">Go!</button>
                            </span>
                        </div>

                        <table id="example2" class="table table-bordered table-hover text-center">

                            <!--==========================第一种方式，手动生成批量修改表============================-->
                            {#                            <thead>#}
                            {#                            <tr>#}
                            {#                                <th style="width: 8%">#}
                            {#                                    <button type="button" class="btn btn-info btn-xs">#}
                            {#                                        <span>批量</span>#}
                            {#                                        <input type="checkbox" name="batch_choose">#}
                            {#                                    </button>#}
                            {#                                </th>#}
                            {#                                <th style="width: 5%">序号</th>#}
                            {#                                <th>学员</th>#}
                            {#                                <th>考勤</th>#}
                            {#                                <th>成绩</th>#}
                            {#                                <th>批语</th>#}
                            {#                            </tr>#}
                            {#                            </thead>#}
                            {#                            <tbody>#}
                            {#                            {% for record in all_records %}#}
                            {#                                <tr>#}
                            {#                                    <td><input type="checkbox" name="choose" value="{{ record.pk }}"></td>#}
                            {#                                    <td>{{ forloop.counter }}</td>#}
                            {#                                    <td>{{ record.student }}</td>#}
                            {#                                    <td>{{ record.get_record_display }}</td>#}
                            {#                                    <td>#}
                            {#                                        <select name="score_{{ record.pk }}" id="">#}
                            {#                                            {% for choice in score_choices %}#}
                            {#                                                {% if record.score == choice.0 %}#}
                            {#                                                    <option value="{{ choice.0 }}" selected>{{ choice.1 }}#}
                            {#                                                        {% else %}#}
                            {#                                                    <option value="{{ choice.0 }}">{{ choice.1 }}#}
                            {#                                                {% endif %}#}
                            {#                                            {% endfor %}#}
                            {#                                        </select>#}
                            {#                                    </td>#}
                            {#                                    <td>#}
                            {#                                        <textarea name="homework_note_{{ record.pk }}" id="" cols="16" rows="1" class="form-control">{{ record.homework_note|default:"" }}</textarea>#}
                            {#                                    </td>#}
                            {#                                </tr>#}
                            {#                            {% endfor %}#}
                            {#                            </tbody>#}



                            <!--==========================第二种方式，通过modelformset生成============================-->
                            {{ all_records.management_form }}  <!-- 这句话一定要加上，固定的昂 不然会报错['ManagementForm data is missing or has been tampered with'] -->
                            <thead>
                            <tr>
                                <th>姓名</th>
                                <th>考勤</th>
                                <th>作业成绩</th>
                                <th>作业评语</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for record in all_records %}
                                <tr>
                                    {{ record.id }}
                                    <td>{{ record.instance.student }}</td>
                                    <td>{{ record.instance.get_record_display }}</td>
                                    <td>{{ record.score }}</td>
                                    <td>{{ record.homework_note }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>

                        </table>
                        <input type="submit" class="btn btn-success pull-right" value="批量提交">
                        {% if not all_records %}
                            <h3 class="text-center">没有相关记录！</h3>
                        {% endif %}

                        <div class="pull-right" style="display:inline-block; width: 120px;margin: 22px 10px">
                            {{ jump_tag|safe }}
                        </div>

                        <div class="pull-right">
                            {{ paginator_tag|safe }}
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
{% endblock content %}
{% block js %}
    {{ block.super }}
{% endblock js %}

{% block customjs %}
    <script>
        $("[name=batch_choose]").click(function () {
            var status = $(this).prop("checked");
            $("[name=choose]").prop('checked', status)
        });
    </script>
    {{ jump_js|safe }}
{% endblock customjs %}

AliCRM/student/templates/student_study_record_list.html
{% extends 'BASE.html' %}
{% load static %}
{% block head %}
    {{ block.super }}
{% endblock head %}
{% block title %}
    学员学习记录
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="text-center"></h3>
                    <form action="" method="get" class="navbar-form navbar-left">
                        <div class="input-group">
                            <div class="input-group-btn btn-info">
                                <select name="condition" id="search" class="btn input-group-sm btn-info"
                                        style="border: 0">
{#                                    <option value="customer">客户名</option>#}
{#                                    <option value="status">跟进状态</option>#}
                                </select>
                            </div>
                            <input type="text" name="q" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button type="submit" id="search-btn" class="btn btn-flat">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                    {% load rbac %}
                        <a href="{% url 'consult_record_add' %}" class="btn btn-primary pull-right">新增记录</a>


                </div>

                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-6">

                        </div>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="input-group" style="width: 220px;margin-bottom: 5px;margin-left: 15px">
                            <select name="operate" id="operate" class="form-control btn-default">
                            </select>
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-warning btn-flat">Go!</button>
                            </span>
                        </div>

                        <table id="example2" class="table table-bordered table-hover text-center">

                            <thead>
                            <tr>
                                <th style="width: 8%">
                                    <button type="button" class="btn btn-info btn-xs"><span>批量</span><input
                                            type="checkbox" name="batch_choose"></button>
                                </th>
                                <th style="width: 5%">序号</th>
                                <th>学员</th>
                                <th>考勤</th>
                                <th>成绩</th>
                                <th>批语</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for record in all_records %}
                                <tr>
                                    <td><input type="checkbox" name="choose" value="{{ record.pk }}"></td>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ record.student }}</td>
                                    <td>{{ record.get_record_display }}</td>
                                    <td>{{ record.score }}</td>
                                    <td>
                                        {{ record.homework_note|default:"暂无" }}
                                    </td>
                                    <td>

                                        <a style="color: #00c3cc;" href="">
                                            <i class="fa fa-edit" aria-hidden="true"></i>
                                        </a>
                                        |
                                        <a style="color: #d9534f;" href="" >
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                        {% if not all_records %}
                            <h3 class="text-center">没有相关记录！</h3>
                        {% endif %}

                        <div class="pull-right" style="display:inline-block; width: 120px;margin: 22px 10px">
                            {{ jump_tag|safe }}
                        </div>

                        <div class="pull-right">
                            {{ paginator_tag|safe }}
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
{% endblock content %}
{% block js %}
    {{ block.super }}
{% endblock js %}

{% block customjs %}
    <script>
        $("[name=batch_choose]").click(function () {
            var status = $(this).prop("checked");
            $("[name=choose]").prop('checked', status)
        });
    </script>
    {{ jump_js|safe }}
{% endblock customjs %}