AliCRM/AliCRM/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crmweb/', include("crmweb.urls")),
    url(r'^rbac/', include("rbac.urls")),
    url(r'^student/', include("student.urls")),
]

AliCRM/crmweb/urls.py
from crmweb.views import accounts, customers
from django.conf.urls import url

urlpatterns = [
    # 注册url
    url(r'^register/', accounts.Register.as_view(), name="register"),
    # 登录url
    url(r"^login/", accounts.Login.as_view(), name="login"),
    # 验证码url
    url(r'^get_auth_img/', accounts.GetAuthImg.as_view(), name="get_auth_img"),
    # 注销url
    url(r'^logout/', accounts.Logout.as_view(), name="logout"),
    # 个人中心url
    url(r'^profile/', accounts.Profile.as_view(), name="profile"),
    # 修改密码url
    url(r'^change_pwd/', accounts.ChangePwd.as_view(), name="change_pwd"),
    # 主页url
    url(r'^index/', customers.Index.as_view(), name="index"),


    # 公户数据url
    url(r'^customer/common/list/', customers.CommonData.as_view(), name="common"),
    # 公户信息添加url
    url(r'^customer/common/add/', customers.CustomerAdd.as_view(), name="customer_common_add"),
    # 公户信息编辑url
    url(r'^customer/common/edit/(\d+)/', customers.CustomerEdit.as_view(), name="customer_common_edit"),
    # 公户信息删除url
    url(r'^customer/common/del/(\d+)/', customers.CustomerDel.as_view(), name="customer_common_del"),


    # 私户数据url
    url(r'^customer/private/list/', customers.CommonData.as_view(), name="private"),  # 使用公户url展示
    # 私户信息添加url
    url(r'^customer/add/', customers.CustomerAdd.as_view(), name="add_customer"),
    # 私户信息编辑url
    url(r'^customer/edit/(\d+)/', customers.CustomerEdit.as_view(), name="edit_customer"),
    # 私户信息删除url
    url(r'^customer/del/(\d+)/', customers.CustomerDel.as_view(), name="del_customer"),


    # 客户数据分析url
    url(r'^customer/charts/(\d+)/', customers.ChartsCustomer.as_view(), name="charts_customer"),

    # 客户跟进数据url
    url(r'^consult/record/list/(\d+)?/?$', customers.ConsultRecord.as_view(), name="consult_record_list"),
    # 客户跟进信息添加url
    url(r'^consult/record/add/', customers.ConsultRecordAddEdit.as_view(), name="consult_record_add"),
    # 客户跟进信息编辑url
    url(r'^consult/record/edit/(\d+)/', customers.ConsultRecordAddEdit.as_view(), name="consult_record_edit"),
    # 客户跟进信息删除url
    url(r'^consult/record/del/(\d+)/', customers.ConsultRecordDel.as_view(), name="consult_record_del"),


    # 报名客户信息展示
    url(r'^enrollment/list/', customers.Enrollment.as_view(), name="enrollment"),
    # 测试路径
    url(r'^test/', customers.Test.as_view(), name="test"),
    # charts图表测试
    url(r'^charts/test', customers.chartstest, name="chartstest"),

]

AliCRM/rbac/urls.py
from rbac.views import permission_distribute
from django.conf.urls import url

urlpatterns = [
    url(r'^permission/distribute/', permission_distribute.PermissionDistribute.as_view(), name="distribute")
]

AliCRM/crmweb/models.py
# Create your models here.
from django.db import models
from multiselectfield import MultiSelectField
# 安装:pip install django-multiselectfield,针对choices多选用的
# from django.utils.safestring import mark_safe

# 课程选择
course_choices = (
    ('Linux', 'Linux高级'),
    ('PythonFullStack', 'Python高级全栈开发'),
    ('BigData', '大数据开发'),
)

# 班级类型
class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

# 客户来源分类
source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

# 报名状态分类
enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

# 客户意向分类
seek_status_choices = (
    ('A', '近期无报名计划'),
    ('B', '1个月内报名'),
    ('C', '2周内报名'),
    ('D', '1周内报名'),
    ('E', '定金'),
    ('F', '到班'),
    ('G', '全款'),
    ('H', '无效'),
)

# 支付类别分类
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

# 考勤分类
attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

# 分数分类
score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


# 客户信息表
class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', default="潜在客户", max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    gender_type = (('male', '男'), ('female', '女'))
    gender = models.CharField("性别", choices=gender_type, max_length=16, default='male', blank=True,
                              null=True)  # 存的是male或者female，字符串

    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)

    phone = models.CharField('手机号', blank=True, null=True, max_length=32)
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True,
                                       null=True)  # self指的就是自己这个表，和下面写法是一样的效果

    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices, blank=True, null=True)  # 多选，并且存成一个列表的格式
    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime', blank=True,
                                  null=True)
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")  # help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", )

    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)  # 考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等

    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)  # 销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    # 用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('rbac.UserInfo', verbose_name="销售", blank=True, null=True)

    # 一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)

    def __str__(self):
        return self.name + ":" + self.qq_name + "(" + self.qq + ")"  # 主要__str__最好是个字符串昂，不然你会遇到很多的坑，还有我们返回的这两个字段填写数据的时候必须写上数据，必然相加会报错，null类型和str类型不能相加等错误信息。

    def get_classlist(self):  # 当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用

        l = []
        for cls in self.class_list.all():
            l.append(str(cls))
        # return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂
        return ",".join(l)  # 纯文本，不用mark_safe也可以昂


# 校区表
class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


# 班级表
class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")  # python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区", on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)  # 不一定什么时候结业，哈哈，所以可为空

    # contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('rbac.UserInfo',
                                      verbose_name="老师")  # 对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)


# 跟进记录表
class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="咨询客户")

    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")

    note = models.TextField(verbose_name="跟进内容...")

    consultant = models.ForeignKey("rbac.UserInfo", verbose_name="跟进人", related_name='records')

    date = models.DateTimeField("跟进日期", auto_now_add=True)

    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


# 登记报名表
class Enrollment(models.Model):
    """报名表"""
    customer = models.ForeignKey('Customer', verbose_name='客户名称')

    why = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)

    expectation = models.TextField("学习期望", max_length=1024, blank=True, null=True)

    enrolled_date = models.DateTimeField(verbose_name="报名日期")

    memo = models.TextField('备注', blank=True, null=True)

    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    school = models.ForeignKey('Campuses')  # 校区表

    enrollment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrollment_class', 'customer')

AliCRM/crmweb/views/accounts.py
from django import views
from rbac import models
from django.contrib import auth
from crmweb.utils import authcode
from crmweb.forms import formAuth
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import (
    render, redirect, reverse, HttpResponse
)

from rbac.service.init_permission import init_permission  # 自定义权限注入函数


# create you views here

# 注册视图类
class Register(views.View):
    def get(self, request):
        return render(request, "register.html")

    def post(self, request):
        data = request.POST
        form_obj = formAuth.RegForm(data)
        if form_obj.is_valid():  # 验证提交数据的合法性
            valid_data = form_obj.cleaned_data
            username = valid_data.get("username")
            # 判断帐号是否已存在
            if models.UserInfo.objects.filter(username=username):
                # 如果存在，给form中的username字段添加一个错误提示。
                form_obj.add_error("username", "帐号已存在")
                return render(request, "register.html", {"form_obj": form_obj})
            else:
                # 帐号可用，去掉多余密码，在数据库创建记录
                del valid_data["r_password"]
                models.UserInfo.objects.create_user(**valid_data)
                return redirect("login")
        else:
            # 数据验证不通过，返回页面和错误提示，保留数据
            return render(request, "register.html", {"form_obj": form_obj})


# 登录视图类
class Login(views.View):
    def get(self, request):
        return render(request, "login.html")

    def post(self, request):
        data = request.POST
        authcode = data.get("authcode")
        username = data.get("username")
        password = data.get("password")
        if request.session.get("authcode").upper() != authcode.upper():
            return JsonResponse({"status": "1"})
        else:
            user = auth.authenticate(username=username, password=password)
            if user:
                # 将用户名存入session中
                request.session["user"] = username

                # 将用户的权限添加到session中
                init_permission(request,username)
                auth.login(request, user)  # 将用户信息添加到session中
                return JsonResponse({"status": "2"})
            else:
                return JsonResponse({"status": "3"})


# 验证码视图类
class GetAuthImg(views.View):
    """获取验证码视图类"""

    def get(self, request):
        data = authcode.get_authcode_img(request)
        print("验证码：",request.session.get("authcode"))
        return HttpResponse(data)


# 注销视图类
class Logout(views.View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        res = super().dispatch(request, *args, **kwargs)
        return res

    def get(self, request):
        auth.logout(request)
        return redirect("login")


# 个人中心
class Profile(views.View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        res = super().dispatch(request, *args, **kwargs)
        return res

    def get(self, request):
        username = request.user.username
        form_obj = formAuth.ChangeForm()
        user_info = models.UserInfo.objects.filter(username=username)[0]
        return render(request, "profile.html", {"user_info": user_info, "form_obj": form_obj})


# 修改密码
class ChangePwd(views.View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        res = super().dispatch(request, *args, **kwargs)
        return res

    def post(self, request):
        form_obj = formAuth.ChangeForm(request.POST)
        # print(request.POST)
        authcode = request.session.get("authcode")
        if request.POST.get("authcode").upper() == authcode.upper():
            if form_obj.is_valid():
                data = form_obj.cleaned_data
                password = data.get("password")
                new_password = data.get("new_password")
                r_new_password = data.get("r_new_password")
                if request.user.check_password(password):
                    if new_password == r_new_password:
                        request.user.set_password(new_password)
                        request.user.save()
                        return JsonResponse({"status": 1000, "info": reverse("login")})
                    else:
                        return JsonResponse({"status": 1001, "info": "两次密码输入不一致！"})
                else:
                    return JsonResponse({"status": 1002, "info": "密码输入错误！"})
            else:
                return JsonResponse({"status": 1003, "info": "输入内容有误！"})
        else:
            return JsonResponse({"status": 1004, "info": "验证码输入有误！"})

AliCRM/crmweb/templates/consult_record_add.html
{% extends 'BASE.html' %}
{% block head %}
    {{ block.super }}
{% endblock head %}
{% block title %}
    新增记录
{% endblock title %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8">
                <form action="" method="post" class="form-horizontal" novalidate>
            {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}" class="control-label col-sm-2">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                <span class="text-danger">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-success pull-right" value="添加">
                </form>
            </div>
        </div>
    </div>

{% endblock content %}
{% block js %}
    {{ block.super }}
{% endblock js %}

AliCRM/crmweb/templates/consult_record_list.html
{% extends 'BASE.html' %}
{% load static %}
{% block head %}
    {{ block.super }}
{% endblock head %}
{% block title %}
    客户跟进信息
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    <form action="" method="get" class="navbar-form navbar-left">
                        <div class="input-group">
                            <div class="input-group-btn btn-info">
                                <select name="condition" id="search" class="btn input-group-sm btn-info"
                                        style="border: 0">
                                    <option value="customer">客户名</option>
                                    <option value="status">跟进状态</option>
                                </select>
                            </div>
                            <input type="text" name="q" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button type="submit" id="search-btn" class="btn btn-flat">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                    {% load rbac %}
                    {% if "/crmweb/consult/record/add/"|has_permission:request %}
                        <a href="{% url 'consult_record_add' %}" class="btn btn-primary pull-right">新增记录</a>
                    {% endif %}

                </div>

                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-6">

                        </div>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="input-group" style="width: 220px;margin-bottom: 5px;margin-left: 15px">
                            <select name="operate" id="operate" class="form-control btn-default">
                                <option value="">选择批量操作</option>
                                <option value="batch_delete">批量删除</option>
                                <option value="batch_update">批量更改客户状态</option>
                            </select>
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-warning btn-flat">Go!</button>
                            </span>
                        </div>


                        <table id="example2" class="table table-bordered table-hover text-center">
                            <thead>
                            <tr>
                                <th style="width: 8%">
                                    <button type="button" class="btn btn-info btn-xs"><span>批量</span><input
                                            type="checkbox" name="batch_choose"></button>
                                </th>
                                <th style="width: 5%">序号</th>
                                <th>客户</th>
                                <th>跟进转态</th>
                                <th>跟进内容</th>
                                <th>跟进人</th>
                                <th>跟进日期</th>
                                {% if "/crmweb/consult/record/edit/1/"|has_permission:request or "/crmweb/consult/record/del/1/"|has_permission:request %}
                                <th>操作</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for record in all_records %}
                                <tr>
                                    <td><input type="checkbox" name="choose" value="{{ record.pk }}"></td>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ record.customer.qq_name }}</td>
                                    <td>{{ record.get_status_display }}</td>
                                    <td>
                                        {{ record.note|default:"暂无" }}
                                    </td>
                                    <td>{{ record.consultant.username|default:'暂无' }}</td>
                                    <td>{{ record.date|date:"Y-m-d" }}</td>
                                {% if "/crmweb/consult/record/edit/1/"|has_permission:request or "/crmweb/consult/record/del/1/"|has_permission:request %}
                                    <td>
                                        {% if "/crmweb/consult/record/edit/1/"|has_permission:request %}
                                        <a style="color: #00c3cc;" href="{% url 'consult_record_edit' record.pk %}">
                                            <i class="fa fa-edit" aria-hidden="true"></i>
                                        </a>
                                        {% endif %}
                                        {% if "/crmweb/consult/record/edit/1/"|has_permission:request and "/crmweb/consult/record/del/1/"|has_permission:request %}
                                        |
                                        {% endif %}
                                        {% if "/crmweb/consult/record/del/1/"|has_permission:request %}
                                        <a style="color: #d9534f;" href="{% url 'consult_record_del' record.pk %}" >
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                        {% endif %}
                                    </td>
                                {% endif %}
                                </tr>
                            {% endfor %}

                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                        {% if not all_records %}
                            <h3 class="text-center">没有相关记录！</h3>
                        {% endif %}

                        <div class="pull-right" style="display:inline-block; width: 120px;margin: 22px 10px">
                            {{ jump_tag|safe }}
                        </div>

                        <div class="pull-right">
                            {{ paginator_tag|safe }}
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
{% endblock content %}
{% block js %}
    {{ block.super }}
{% endblock js %}

{% block customjs %}
    <script>
        $("[name=batch_choose]").click(function () {
            var status = $(this).prop("checked");
            $("[name=choose]").prop('checked', status)
        });
    </script>
    {{ jump_js|safe }}
{% endblock customjs %}

AliCRM/crmweb/templates/customers_common_list.html
{% extends 'BASE.html' %}
{% load static %}
{% block head %}
    {{ block.super }}
{% endblock head %}
{% block title %}
    {% if flag %}
        公户信息展示
    {% else %}
        私户信息展示
    {% endif %}
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    <form action="" method="get" class="navbar-form navbar-left">
                        <div class="input-group">
                            <div class="input-group-btn btn-info">
                                <select name="condition" id="search" class="btn input-group-sm btn-info"
                                        style="border: 0">
                                    <option value="" readonly>条件</option>
                                    <option value="qq_name">昵称</option>
                                    <option value="qq">QQ号</option>
                                </select>
                            </div>
                            <input type="text" name="q" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button type="submit" id="search-btn" class="btn btn-flat">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                    {% load rbac %}
                    {% if "/crmweb/customer/common/add/"|has_permission:request %}
                    <a href="{% url 'customer_common_add' %}" class="btn btn-primary pull-right">新增客户</a>
                    {% endif %}

                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-6">
                        </div>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="input-group" style="width: 220px;margin-bottom: 5px;margin-left: 15px">
                            <select name="operate" id="operate" class="form-control btn-default">
                                <option value="">选择批量操作</option>
                                <option value="batch_delete">批量删除</option>
                                <option value="batch_update">批量更改客户状态</option>
                                {% if flag %}
                                    <option value="batch_c2p">批量公转私</option>
                                {% else %}
                                    <option value="batch_c2p">批量公转私</option>
                                {% endif %}
                            </select>
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-warning btn-flat">Go!</button>
                            </span>
                        </div>
                        {% if name_str %}
                            <div class="btn text-danger" id="choose_error">顾客:{{ name_str }}已经被选走了</div>
                        {% endif %}


                        <table id="example2" class="table table-bordered table-hover text-center">
                            <thead>
                            <tr>
                                <th style="width: 6%">
                                    <span>
                                        <i class="fa fa-check-square-o"></i>
                                        <input type="checkbox" name="batch_choose">
                                    </span>
                                </th>
                                <th style="width: 5%">序号</th>
                                <th>qq</th>
                                <th>姓名</th>
                                <th>电话</th>
                                <th>来源</th>
                                <th>咨询课程</th>
                                <th>客户状态</th>
                                <th>销售老师</th>
                                {% if not flag %}
                                    <th>跟进信息</th>
                                {% endif %}
                                {% if "/crmweb/customer/common/edit/1/"|has_permission:request or "/crmweb/customer/common/del/1/"|has_permission:request %}
                                <th>操作</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for customer in all_customers %}
                                <tr>
                                    <td><input type="checkbox" name="choose" value="{{ customer.pk }}"></td>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ customer.qq }}</td>
                                    <td>{{ customer.qq_name }}</td>
                                    <td>
                                        {{ customer.phone|default:"暂无" }}
                                    </td>
                                    <td>{{ customer.get_source_display|default:'暂无' }}</td>
                                    <td>{{ customer.get_course_display|default:"暂无" }}</td>
                                    <td>{{ customer.get_status_display }}</td>
                                    <td>{{ customer.consultant.username|default:'暂无' }}</td>
                                    {% if not flag %}
                                        <td><a href="{% url 'consult_record' customer.pk %}">详情</a></td>
                                    {% endif %}
                                    {% if "/crmweb/customer/common/edit/1/"|has_permission:request or "/crmweb/customer/common/del/1/"|has_permission:request %}
                                    <td>
                                        {% if "/crmweb/customer/common/edit/1/"|has_permission:request %}
                                        <a style="color: #00c3cc;" href="{% url 'consult_record_edit' customer.pk %}">
                                            <i class="fa fa-edit" aria-hidden="true"></i>
                                        </a>
                                        {% endif %}
                                        {% if "/crmweb/customer/common/edit/1/"|has_permission:request and "/crmweb/customer/common/del/1/"|has_permission:request %}
                                        |
                                        {% endif %}
                                        {% if "/crmweb/customer/common/del/1/"|has_permission:request %}
                                        <a style="color: #d9534f;" href="{% url 'consult_record_del' customer.pk %}">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                        {% endif %}
                                    </td>
                                {% endif %}
                                </tr>
                            {% endfor %}

                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                        {% if not all_customers %}
                            <h3 class="text-center">没有相关记录！</h3>
                        {% endif %}
                    </form>


                    <div class="pull-right" style="display:inline-block; width: 120px;margin: 22px 10px">
                        {{ jump_tag|safe }}
                    </div>

                    <div class="pull-right">
                        {{ paginator_tag|safe }}
                    </div>


                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
{% endblock content %}
{% block js %}
    {{ block.super }}
{% endblock js %}

{% block customjs %}
    <script>
        $("[name=batch_choose]").click(function () {
            var status = $(this).prop("checked");
            $("[name=choose]").prop('checked', status)
        });
        $("#choose_error").click(function () {
            $("#choose_error").css("display", "none");
        })
    </script>
    {{ jump_js|safe }}
{% endblock customjs %}